name: docker build
on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-22.04
        env:
            ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION: node16
            ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
        strategy:
            fail-fast: false
            matrix:
                include:
                    - image: centos:7
                      run: |
                          sed -i 's,^mirrorlist=,#,; s,^#baseurl=http://mirror\.centos\.org/centos/$releasever,baseurl=https://vault.centos.org/7.9.2009,' /etc/yum.repos.d/CentOS-Base.repo
                          yum install -y kernel-devel kernel gcc make elfutils-libelf-devel
                    - image: almalinux:8
                      run: yum install -y kernel-devel kernel gcc make elfutils-libelf-devel
                    - image: rockylinux:8
                      run: yum install -y kernel-devel kernel gcc make elfutils-libelf-devel
                    - image: quay.io/centos/centos:stream9
                      run: dnf install -y --nobest kernel-devel-matched gcc make
                    - image: fedora:latest
                      run: dnf install -y kernel-devel kernel gcc make elfutils-libelf-devel
                    - image: alt:sisyphus
                      run: |
                          apt-get update && apt-get install -y gcc make libelf-devel && \
                          apt-get install -y kernel-headers-modules-mainline || apt-get install -y kernel-headers-modules-latest1
                    - image: registry.opensuse.org/opensuse/tumbleweed
                      run: zypper -n install -y gcc make kernel-default-devel awk
                    - image: registry.opensuse.org/opensuse/leap
                      run: zypper -n install -y gcc make kernel-default-devel tar gzip

        container:
            image: ${{ matrix.image }}
            options: --security-opt seccomp=unconfined

        steps:
            - run: cat /etc/os-release
            - run: ${{ matrix.run }}
            - uses: actions/checkout@v3
            - run: make -j$(nproc) KERNELRELEASE=$(cd /lib/modules; ls)

# vim: sw=4
